[theme]
primaryColor = "#294380"          # Azul vibrante (botões de ação)
backgroundColor = "#69d2cd"       # Cinza quase branco (fundo limpo)
secondaryBackgroundColor = "#b9f1d6" # Cinza azulado (campos de input)
textColor = "#0d0f36"             # Azul marinho escuro (leitura fácil)